### PR TITLE
Gab

### PR DESCRIPTION
**Pull request by gabsun**
1. I added a "name" field to all the files listed in TestInput.json - I'm guessing the R code will crash if these are not present in production. It would have been silly to recode without putting this facility in - the plots need to have this information on them.
2. TestInput.json now contains two example benchmark files (i.e. different model outputs for the same site), and I added these files to the repository as TestBenchmark1.nc and TestBenchmark2.nc. These needn't be provided in production - the R code will just check if they're there and use them (add lines to relevant plots) if they are. The "number" field is intended to indicate the rank the user gave to the benchmark - i.e. if this was the user's first nominated benchmark for their MO, number = '1'. in reality this will be a number between 1 and 3 (but passed as a character of course).
3. I changed the test site data files to be a site for which I already had two other MOs available to be benchmarks - file sizes are similar to before.
4. Errors are now part of the output list, as you suggested. Each list item now has an 'error' field which contains a string. There is also a 'bencherror' string, which reports what, if anything, went wrong with adding the user's nominated benchmarks to the plots. For example, some plots (at least for the moment) cannot add benchmark information, and this is noted in the bencherror string for these analyses. Maybe a table with two columns is still warranted for this information.
5. In addition to the "type" field for each analysis in the output structure, I've added an 'analysistype' and 'variablename' field. I will want these when we build the report generation feature - feel free to ignore for now (happy to chat more about the scope of this if you like - I think it's relatively straightforward).
6. Similar to 5, there is a also a 'metrics' field in the output structure which will return 'scores' for the MO in each analysis, which I'll want for report generation. These are just hard coded for now (rather than reporting meaningful values) - it's just the communication structure to get the info back to the database. At some point when we implement report generation, we will want to save and later retrieve this information at a user's request.
7. SingleSiteExperiment.R is coded to allow use of the 'parallel' package if we can build it on the analysis server. It's checked in with this stuff commented out, but just three or four comments need to be removed to turn it into the parallel version should that package be available. With this relatively short test data set, on my laptop, it drops total analysis time from ~65 seconds to 27 and it will only come closer to scaling to the number of cores for larger datasets.
8. I've left a 'system.time' call and print statement in the TestSingleSiteExperiment.R script to let us see how much the parallel option helps in production.
9. I assume no significance was attached to what was printed to screen - it's changed a little.

### CODE REVIEW

**Comment by edenduthie** [comment]
Hi Gab,

Great! You can also test out your new script on the test server at
http://115.146.84.161, the same test data from the git project is already
loaded in the public data set. All you need to do is upload the different
script to the experiment.

Cheers,

Eden

**Comment by gabsun** [comment]
Hi Eden,

Does that mean the new R package is already built there too? I need that for the new script, as well as the "name" field on files that are sent to the R script.

Thanks

Gab

On 25 Mar 2014, at 10:48 am, Eden Duthie notifications@github.com wrote:

> Hi Gab,
> 
> Great! You can also test out your new script on the test server at
> http://115.146.84.161, the same test data from the git project is already
> loaded in the public data set. All you need to do is upload the different
> script to the experiment.
> 
> Cheers,
> 
> Eden
> 
> On Tue, Mar 25, 2014 at 8:35 AM, Gab Abramowitz notifications@github.comwrote:
> 
> > 1.
> > 
> > I added a "name" field to all the files listed in TestInput.json - I'm
> > guessing the R code will crash if these are not present in production. It
> > would have been silly to recode without putting this facility in - the
> > plots need to have this information on them.
> > 2.
> > 
> > TestInput.json now contains two example benchmark files (i.e.
> > different model outputs for the same site), and I added these files to the
> > repository as TestBenchmark1.nc and TestBenchmark2.nc. These needn't be
> > provided in production - the R code will just check if they're there and
> > use them (add lines to relevant plots) if they are. The "number" field is
> > intended to indicate the rank the user gave to the benchmark - i.e. if this
> > was the user's first nominated benchmark for their MO, number = '1'. in
> > reality this will be a number between 1 and 3 (but passed as a character of
> > course).
> > 3.
> > 
> > I changed the test site data files to be a site for which I already
> > had two other MOs available to be benchmarks - file sizes are similar to
> > before.
> > 4.
> > 
> > Errors are now part of the output list, as you suggested. Each list
> > item now has an 'error' field which contains a string. There is also a
> > 'bencherror' string, which reports what, if anything, went wrong with
> > adding the user's nominated benchmarks to the plots. For example, some
> > plots (at least for the moment) cannot add benchmark information, and this
> > is noted in the bencherror string for these analyses. Maybe a table with
> > two columns is still warranted for this information.
> > 5.
> > 
> > In addition to the "type" field for each analysis in the output
> > structure, I've added an 'analysistype' and 'variablename' field. I will
> > want these when we build the report generation feature - feel free to
> > ignore for now (happy to chat more about the scope of this if you like - I
> > think it's relatively straightforward).
> > 6.
> > 
> > Similar to 5, there is a also a 'metrics' field in the output
> > structure which will return 'scores' for the MO in each analysis, which
> > I'll want for report generation. These are just hard coded for now (rather
> > than reporting meaningful values) - it's just the communication structure
> > to get the info back to the database. At some point when we implement
> > report generation, we will want to save and later retrieve this information
> > at a user's request.
> > 7.
> > 
> > SingleSiteExperiment.R is coded to allow use of the 'parallel' package
> > if we can build it on the analysis server. It's checked in with this stuff
> > commented out, but just three or four comments need to be removed to turn
> > it into the parallel version should that package be available. With this
> > relatively short test data set, on my laptop, it drops total analysis time
> > from ~65 seconds to 27 and it will only come closer to scaling to the
> > number of cores for larger datasets.
> > 8.
> > 
> > I've left a 'system.time' call and print statement in the
> > TestSingleSiteExperiment.R script to let us see how much the parallel
> > option helps in production.
> > 9.
> > 
> > I assume no significance was attached to what was printed to screen -
> > it's changed a little.
> > 
> > ---
> > 
> > You can merge this Pull Request by running
> > 
> > git pull https://github.com/edenduthie/palsR Gab
> > 
> > Or view, comment on, or merge it at:
> > 
> > https://github.com/edenduthie/palsR/pull/1
> > Commit Summary
> > - PNG resolution and UUID changes
> > - Removed "old" versions of package functions
> > - First working version of new R code
> > 
> > File Changes
> > - _M_ pals/DESCRIPTIONhttps://github.com/edenduthie/palsR/pull/1/files#diff-0(4)
> > - _M_ pals/R/AnalysisAnnualCycle.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-1(97)
> > - _M_ pals/R/AnalysisAveragingWindow.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-2(18)
> > - _M_ pals/R/AnalysisDiurnalCycle.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-3(121)
> > - _M_ pals/R/AnalysisPdf.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-4(115)
> > - _M_ pals/R/AnalysisScatter.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-5(33)
> > - _M_ pals/R/AnalysisTaylorDiagram.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-6(27)
> > - _M_ pals/R/AnalysisTimeseries.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-7(135)
> > - _D_ pals/R/BenchmarkEmpirical.R.oldhttps://github.com/edenduthie/palsR/pull/1/files#diff-8(381)
> > - _A_ pals/R/DistributeAnalyses.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-9(194)
> > - _D_ pals/R/GetModelVariableName.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-10(56)
> > - _M_ pals/R/LoadNetcdfVariable.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-11(235)
> > - _D_ pals/R/PALSUtils.R.oldhttps://github.com/edenduthie/palsR/pull/1/files#diff-12(228)
> > - _M_ pals/R/PALSchecks.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-13(24)
> > - _M_ pals/R/PALSconstants.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-14(87)
> > - _M_ pals/R/PALSutils.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-15(203)
> > - _M_ scripts/SingleSiteExperiment.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-16(241)
> > - _A_ scripts/TestBenchmark1.nchttps://github.com/edenduthie/palsR/pull/1/files#diff-17(0)
> > - _A_ scripts/TestBenchmark2.nchttps://github.com/edenduthie/palsR/pull/1/files#diff-18(0)
> > - _M_ scripts/TestDataSetFlux.nchttps://github.com/edenduthie/palsR/pull/1/files#diff-19(0)
> > - _M_ scripts/TestDataSetMet.nchttps://github.com/edenduthie/palsR/pull/1/files#diff-20(0)
> > - _M_ scripts/TestInput.jsonhttps://github.com/edenduthie/palsR/pull/1/files#diff-21(25)
> > - _M_ scripts/TestModelOutput.nchttps://github.com/edenduthie/palsR/pull/1/files#diff-22(0)
> > - _M_ scripts/TestSingleSiteExperiment.Rhttps://github.com/edenduthie/palsR/pull/1/files#diff-23(3)
> > 
> > Patch Links:
> > - https://github.com/edenduthie/palsR/pull/1.patch
> > - https://github.com/edenduthie/palsR/pull/1.diff
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/edenduthie/palsR/pull/1
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Gab Abramowitz
Climate Change Research Centre
University of New South Wales
gabsun@gmail.com / gabriel@unsw.edu.au
ph: +61 2 9385 8958
mobile: +61 403 139402

**Comment by edenduthie** [comment]
Hi Gab,

Yes, I have installed it on the new server.

Where should the name field come from? Is it the file name, or data set /
model output name? Add it as a new task to Trello so it doesn't get lost.

Cheers,

Eden

**Comment by yoichi01** [comment]
Hi Eden,

Should I be receiving these correspondences?

How are your little one and your Mrs? :)

Yoichi

On 26 Mar 2014, at 11:08 am, Eden Duthie notifications@github.com wrote:

> Hi Gab,
> 
> Yes, I have installed it on the new server.
> 
> Where should the name field come from? Is it the file name, or data set /
> model output name? Add it as a new task to Trello so it doesn't get lost.
> 
> Cheers,
> 
> Eden

---

Yoichi Takayama, PhD
Research Officer
Climate Change Research Centre
Level 4 Mathews Building
University of New South Wales
Sydney, Australia, 2052
Phone (CCRC): +61 2 9385 8963 

## Fax (CCRC): +61 2 9385 8969

UNSW  ABN 57 195 873 179, CRICOS Provider 00098G
IMPORTANT: This email and any attachment(s) transmitted with it are intended solely for the use of the addressee(s) and may contain information that is confidential or subject to legal privilege. If you receive this email in error, please disregard the contents of the email and attachment(s), delete them and notify the sender immediately. Please note that any copying, distribution or use of this email is prohibited. Any views expressed in this message are those of the individual sender, except where the sender expressly, and with authority, states them to be the view of The University of New South Wales. Before opening any attachments, please check for viruses.

**Comment by edenduthie** [comment]
Hi Yoichi,

How are you!

You are receiving them as you are listed as a contributor to pals still.
Would you like me to remove you?

Sarah is doing great! She has just turned 6 months and is getting a lot
more active.

Nice to year from you.

Cheers,

Eden

**Comment by yoichi01** [comment]
Hi Eden,

Ah, I see.

No, you don't have to remove me as yet :).

Although I am not contributing to the new set-up and am not sure how it may be useful in the future, I will keep an eye on for a little more while.

6 months! You must have gotten use to be parents. :)

She must be a lot of fun now. I imagine that she probably is not sleep/cry/eat life-form anymore and developing personality?

Cheers,
Yoichi

On 26 Mar 2014, at 11:37 am, Eden Duthie notifications@github.com wrote:

> Hi Yoichi,
> 
> How are you!
> 
> You are receiving them as you are listed as a contributor to pals still.
> Would you like me to remove you?
> 
> Sarah is doing great! She has just turned 6 months and is getting a lot
> more active.
> 
> Nice to year from you.
> 
> Cheers,
> 
> Eden

---

Yoichi Takayama, PhD
Research Officer
Climate Change Research Centre
Level 4 Mathews Building
University of New South Wales
Sydney, Australia, 2052
Phone (CCRC): +61 2 9385 8963 

## Fax (CCRC): +61 2 9385 8969

UNSW  ABN 57 195 873 179, CRICOS Provider 00098G
IMPORTANT: This email and any attachment(s) transmitted with it are intended solely for the use of the addressee(s) and may contain information that is confidential or subject to legal privilege. If you receive this email in error, please disregard the contents of the email and attachment(s), delete them and notify the sender immediately. Please note that any copying, distribution or use of this email is prohibited. Any views expressed in this message are those of the individual sender, except where the sender expressly, and with authority, states them to be the view of The University of New South Wales. Before opening any attachments, please check for viruses.

**Comment by gabsun** [comment]
Hi Eden,

Okay, added to Trello as high priority - it’ll allow me to work on the R code whenever I get the time while you deal with other things.

Gab

On 26 Mar 2014, at 11:08 am, Eden Duthie notifications@github.com wrote:

> Hi Gab,
> 
> Yes, I have installed it on the new server.
> 
> Where should the name field come from? Is it the file name, or data set /
> model output name? Add it as a new task to Trello so it doesn't get lost.
> 
> Cheers,
> 
> Eden
> 
> On Tue, Mar 25, 2014 at 6:56 PM, Gab Abramowitz notifications@github.comwrote:
> 
> > Hi Eden,
> > 
> > Does that mean the new R package is already built there too? I need that
> > for the new script, as well as the "name" field on files that are sent to
> > the R script.
> > 
> > Thanks
> > 
> > Gab
> > 
> > On 25 Mar 2014, at 10:48 am, Eden Duthie notifications@github.com
> > wrote:
> > 
> > > Hi Gab,
> > > 
> > > Great! You can also test out your new script on the test server at
> > > http://115.146.84.161, the same test data from the git project is
> > > already
> > > loaded in the public data set. All you need to do is upload the
> > > different
> > > script to the experiment.
> > > 
> > > Cheers,
> > > 
> > > Eden
> > > 
> > > On Tue, Mar 25, 2014 at 8:35 AM, Gab Abramowitz <
> > > notifications@github.com>wrote:
> > > 
> > > > 1.
> > > > 
> > > > I added a "name" field to all the files listed in TestInput.json - I'm
> > > > guessing the R code will crash if these are not present in production.
> > > > It
> > > > would have been silly to recode without putting this facility in - the
> > > > plots need to have this information on them.
> > > > 2.
> > > > 
> > > > TestInput.json now contains two example benchmark files (i.e.
> > > > different model outputs for the same site), and I added these files to
> > > > the
> > > > repository as TestBenchmark1.nc and TestBenchmark2.nc. These needn't
> > > > be
> > > > provided in production - the R code will just check if they're there
> > > > and
> > > > use them (add lines to relevant plots) if they are. The "number" field
> > > > is
> > > > intended to indicate the rank the user gave to the benchmark - i.e. if
> > > > this
> > > > was the user's first nominated benchmark for their MO, number = '1'.
> > > > in
> > > > reality this will be a number between 1 and 3 (but passed as a
> > > > character of
> > > > course).
> > > > 3.
> > > > 
> > > > I changed the test site data files to be a site for which I already
> > > > had two other MOs available to be benchmarks - file sizes are similar
> > > > to
> > > > before.
> > > > 4.
> > > > 
> > > > Errors are now part of the output list, as you suggested. Each list
> > > > item now has an 'error' field which contains a string. There is also a
> > > > 'bencherror' string, which reports what, if anything, went wrong with
> > > > adding the user's nominated benchmarks to the plots. For example, some
> > > > plots (at least for the moment) cannot add benchmark information, and
> > > > this
> > > > is noted in the bencherror string for these analyses. Maybe a table
> > > > with
> > > > two columns is still warranted for this information.
> > > > 5.
> > > > 
> > > > In addition to the "type" field for each analysis in the output
> > > > structure, I've added an 'analysistype' and 'variablename' field. I
> > > > will
> > > > want these when we build the report generation feature - feel free to
> > > > ignore for now (happy to chat more about the scope of this if you like
> > > > - I
> > > >   think it's relatively straightforward).
> > > >   6.
> > > > 
> > > > Similar to 5, there is a also a 'metrics' field in the output
> > > > structure which will return 'scores' for the MO in each analysis,
> > > > which
> > > > I'll want for report generation. These are just hard coded for now
> > > > (rather
> > > > than reporting meaningful values) - it's just the communication
> > > > structure
> > > > to get the info back to the database. At some point when we implement
> > > > report generation, we will want to save and later retrieve this
> > > > information
> > > > at a user's request.
> > > > 7.
> > > > 
> > > > SingleSiteExperiment.R is coded to allow use of the 'parallel' package
> > > > if we can build it on the analysis server. It's checked in with this
> > > > stuff
> > > > commented out, but just three or four comments need to be removed to
> > > > turn
> > > > it into the parallel version should that package be available. With
> > > > this
> > > > relatively short test data set, on my laptop, it drops total analysis
> > > > time
> > > > from ~65 seconds to 27 and it will only come closer to scaling to the
> > > > number of cores for larger datasets.
> > > > 8.
> > > > 
> > > > I've left a 'system.time' call and print statement in the
> > > > TestSingleSiteExperiment.R script to let us see how much the parallel
> > > > option helps in production.
> > > > 9.
> > > > 
> > > > I assume no significance was attached to what was printed to screen -
> > > > it's changed a little.
> > > > 
> > > > ---
> > > > 
> > > > You can merge this Pull Request by running
> > > > 
> > > > git pull https://github.com/edenduthie/palsR Gab
> > > > 
> > > > Or view, comment on, or merge it at:
> > > > 
> > > > https://github.com/edenduthie/palsR/pull/1
> > > > Commit Summary
> > > > - PNG resolution and UUID changes
> > > > - Removed "old" versions of package functions
> > > > - First working version of new R code
> > > > 
> > > > File Changes
> > > > - _M_ pals/DESCRIPTION<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-0>(4)
> > > > - _M_ pals/R/AnalysisAnnualCycle.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-1>(97)
> > > > - _M_ pals/R/AnalysisAveragingWindow.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-2>(18)
> > > > - _M_ pals/R/AnalysisDiurnalCycle.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-3>(121)
> > > > - _M_ pals/R/AnalysisPdf.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-4>(115)
> > > > - _M_ pals/R/AnalysisScatter.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-5>(33)
> > > > - _M_ pals/R/AnalysisTaylorDiagram.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-6>(27)
> > > > - _M_ pals/R/AnalysisTimeseries.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-7>(135)
> > > > - _D_ pals/R/BenchmarkEmpirical.R.old<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-8>(381)
> > > > - _A_ pals/R/DistributeAnalyses.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-9>(194)
> > > > - _D_ pals/R/GetModelVariableName.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-10>(56)
> > > > - _M_ pals/R/LoadNetcdfVariable.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-11>(235)
> > > > - _D_ pals/R/PALSUtils.R.old<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-12>(228)
> > > > - _M_ pals/R/PALSchecks.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-13>(24)
> > > > - _M_ pals/R/PALSconstants.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-14>(87)
> > > > - _M_ pals/R/PALSutils.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-15>(203)
> > > > - _M_ scripts/SingleSiteExperiment.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-16>(241)
> > > > - _A_ scripts/TestBenchmark1.nc<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-17>(0)
> > > > - _A_ scripts/TestBenchmark2.nc<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-18>(0)
> > > > - _M_ scripts/TestDataSetFlux.nc<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-19>(0)
> > > > - _M_ scripts/TestDataSetMet.nc<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-20>(0)
> > > > - _M_ scripts/TestInput.json<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-21>(25)
> > > > - _M_ scripts/TestModelOutput.nc<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-22>(0)
> > > > - _M_ scripts/TestSingleSiteExperiment.R<
> > > >   https://github.com/edenduthie/palsR/pull/1/files#diff-23>(3)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/edenduthie/palsR/pull/1.patch
> > > > - https://github.com/edenduthie/palsR/pull/1.diff
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/edenduthie/palsR/pull/1>
> > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub.
> > 
> > Gab Abramowitz
> > Climate Change Research Centre
> > University of New South Wales
> > gabsun@gmail.com / gabriel@unsw.edu.au
> > ph: +61 2 9385 8958
> > mobile: +61 403 139402
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/edenduthie/palsR/pull/1#issuecomment-38538402
> > .
> > 
> > —
> > Reply to this email directly or view it on GitHub.

Gab Abramowitz
Climate Change Research Centre
University of New South Wales
gabsun@gmail.com / gabriel@unsw.edu.au
ph: +61 2 9385 8958
mobile: +61 403 139402

**Pull request merged**
